/**
 * @file CodeEditorOptions.ts
 */

export const editorOptions: any = {
  readOnly: false,
  minimap: { enabled: false },
  fontSize: 13,
  lineHeight: 20,
  fontFamily: 'JetBrains Mono, Menlo, Monaco, Consolas, monospace',
  scrollBeyondLastLine: false,
  automaticLayout: true,
  padding: { top: 16, bottom: 16 },
  lineNumbers: 'on',
  lineNumbersMinChars: 3,
  glyphMargin: false,
  folding: true,
  lineDecorationsWidth: 10,
  renderLineHighlight: 'all',
  selectionHighlight: true,
  multiCursorModifier: 'alt',
  cursorBlinking: 'smooth',
  cursorSmoothCaretAnimation: "on",
  smoothScrolling: true,
  wordWrap: 'on',
  scrollbar: {
    vertical: 'visible',
    horizontal: 'visible',
    useShadows: false,
    verticalScrollbarSize: 6,
    horizontalScrollbarSize: 6,
    verticalHasArrows: false,
    horizontalHasArrows: false,
  },
  fixedOverflowWidgets: true,
  fontLigatures: true,
  roundedSelection: true,
  overviewRulerLanes: 0,
  overviewRulerBorder: false,
  hideCursorInOverviewRuler: true,
  renderFinalNewline: "on",
  occurrenceHighlight: "on",
  renderWhitespace: "none",
  bracketPairColorization: { enabled: true }
};
